<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('New section') ?></h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    <p>
                        <label for="name">Name: </label>
                        <input type="text" name="name" id="name"/>
                    </p>

                    <p>
                        <input type="submit" value="Create"/>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>