<div class="row">
    <div class="col-md-4">
        <table class="table">
            <thead>
            <tr>
                <th><?php echo $this->translate('Id') ?></th>
                <th><?php echo $this->translate('Name') ?></th>
                <th><?php echo $this->translate('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->sections as $section) { ?>
                <tr>
                    <td><?php echo $section->getId(); ?></td>
                    <td><?php echo $section->getName(); ?></td>
                    <td>
                        <a href="/application/section/read?id=<?php echo $section->getId(); ?>"><?php echo $this->translate('View') ?></a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>