<div class="row">
    <div class="col-md-4">
        <table>
            <tr>
                <td><?php echo $this->translate('Id') ?></td>
                <td><?php echo $this->translate('Name') ?></td>
                <td><?php echo $this->translate('Action') ?></td>
            </tr>
            <?php foreach ($this->sections as $section) { ?>
                <tr>
                    <td><?php echo $section->getId(); ?></td>
                    <td><?php echo $section->getName(); ?></td>
                    <td><a href="/application/section/read?id=<?php echo $section->getId(); ?>"><?php echo $this->translate('View') ?></a></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>