<div class="row">
    <div class="col-md-4">
        <h1><?php echo $this->section->getName(); ?></h1>

        <table>
            <th>
                <tr><?php echo $this->translate('Id') ?></tr>
                <tr><?php echo $this->translate('Name') ?></tr>
                <tr><?php echo $this->translate('Status') ?></tr>
            </th>
            <?php foreach ($this->section->getTasks() as $task) { ?>
                <tr>
                    <td><?php echo $task->getId(); ?></td>
                    <td><?php echo $task->getName(); ?></td>
                    <td><?php echo $task->getStatus(); ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>