<div class="row">

    <div class="col-md-2">
        <div class="panel panel-default">
        </div>
    </div>

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('New task') ?></h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    <p>
                        <label for="name">Name: </label>
                        <input type="text" name="name" id="name"/>
                    </p>

                    <p>
                        <label for="section">Section: </label>
                        <select name="section" id="section">
                            <?php foreach ($this->sections as $section): ?>
                                <option value="<?= $section->getId(); ?>"><?= $section->getName(); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </p>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-2">
        <div class="panel panel-default">
        </div>
    </div>
</div>