<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Generic pane title') ?></h3>
            </div>
            <div class="panel-body">
                <p>Hello, dear <?= $this->user->getFullName(); ?></p>
                <p>Wonna <a href="/application/user/logout">logout</a>?</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Latest activity') ?></h3>
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Update profile') ?></h3>
            </div>
            <div class="panel-body">
                <p>* DOESN'T WORK</p>
                <?php if ($this->message): ?>
                    <p>
                        <?= $this->translate($this->message); ?>
                    </p>
                <?php endif; ?>
                <form action="/application/user/index" method="post">
                    <p>
                        <label for="login">Login:</label>
                        <input type="text" name="login" id="login" value="<?= $this->user->getLogin(); ?>"/>
                    </p>

                    <p>
                        <label for="full-name">Full name:</label>
                        <input type="text" name="full-name" id="full-name" value="<?= $this->user->getFullName(); ?>"/>
                    </p>

                    <p>
                        <label for="password">New Password:</label>
                        <input type="text" name="password" id="password"/>
                    </p>

                    <p>
                        <input type="submit" value="Submit"/>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>