<div class="row">

    <div class="col-md-4">
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Login') ?></h3>
            </div>
            <div class="panel-body">
                <?php if ($this->message): ?>
                    <p>
                        <?= $this->translate($this->message); ?>
                    </p>
                <?php endif; ?>
                <form action="" method="post">
                    <p>
                        <label for="login">Login:</label>
                        <input type="text" name="login" id="login"/>
                    </p>

                    <p>
                        <label for="password">Password:</label>
                        <input type="text" name="password" id="password"/>
                    </p>

                    <p>
                        <input type="submit" value="Submit"/>
                    </p>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-4">
    </div>
</div>